using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class JobPreferencesGui : Control
    {
        [Dependency] private readonly IEntityManager _entManager = default!;

        public JobPreferencesGui(IResourceCache resourceCache)
        {
            RobustXamlLoader.Load(this);

            var panelTex = resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            //IoCManager.InjectDependencies(this);
        }
    }
}
