using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client.Lobby.UI;


[GenerateTypedNameReferences]
public sealed partial class JobPreferences : Control
{
    private readonly IEntityManager _entManager;
    private readonly IPrototypeManager _prototypeManager;

    public JobPreferences(IEntityManager entityManager, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _entManager = entityManager;
        _prototypeManager = prototypeManager;
        //IoCManager.InjectDependencies(this);
    }
}
