using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class JobPreferencesGui : Control
    {
        [Dependency] private readonly IEntityManager _entManager = default!;

        public JobPreferencesGui()
        {
            RobustXamlLoader.Load(this);
            //IoCManager.InjectDependencies(this);
        }
    }
}
