using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client.Lobby.UI;


[GenerateTypedNameReferences]
public sealed partial class JobPreferences : Control
{
    private readonly IEntityManager _entManager;
    private readonly IPrototypeManager _prototypeManager;
    private readonly IResourceCache _resourceCache;

    public JobPreferences(IEntityManager entityManager, IPrototypeManager prototypeManager, IResourceCache resourceCache)
    {
        RobustXamlLoader.Load(this);
        _entManager = entityManager;
        _prototypeManager = prototypeManager;
        _resourceCache = resourceCache;

        var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
        var back = new StyleBoxTexture
        {
            Texture = panelTex,
            Modulate = new Color(37, 37, 42)
        };
        back.SetPatchMargin(StyleBox.Margin.All, 10);

        BackgroundPanel.PanelOverride = back;
        //IoCManager.InjectDependencies(this);
    }
}
