using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    // EE: Job Preferences
    [GenerateTypedNameReferences]
    public sealed partial class JobPreferencesGui : Control
    {
        private readonly IEntityManager _entManager;
        private readonly IPrototypeManager _protomanager;

        public JobPreferencesGui(IEntityManager entManager, IPrototypeManager protoManager,IResourceCache resourceCache, JobPreferenceEditor jobEditor)
        {
            RobustXamlLoader.Load(this);
            _entManager = entManager;
            _protomanager = protoManager;

            var panelTex = resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            JobPreferencesEditor.AddChild(jobEditor);

            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();
            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();
            //IoCManager.InjectDependencies(this);
        }
    }
}
